### ISSUE TITLE
[아이템 1] 생성자 대신 정적 팩터리 메서드를 고려하라

### ISSUE THREAD

**Issue by syunyun** [org-study-java/effective-java#1]
[아이템 1] 생성자 대신 정적 팩터리 메서드를 고려하라

**Comment by syunyun** [comment]
OOP에서 상속보다는 컴포지션을 사용하라는 말을 많이 들어봤다. 아이템1에서도 정적 팩토리 메서드만 제공하면 객체를 생성할때 상속을 강제로 막을수 있고 컴포지션을이용하도록 강제할 수 있다고 말하는데 컴포지션이 상속보다 좋은점은?

**Comment by DongjunLim** [comment]
> OOP에서 상속보다는 컴포지션을 사용하라는 말을 많이 들어봤다. 아이템1에서도 정적 팩토리 메서드만 제공하면 객체를 생성할때 상속을 강제로 막을수 있고 컴포지션을이용하도록 강제할 수 있다고 말하는데 컴포지션이 상속보다 좋은점은 뭘까.......?????

상속은 자식 클래스의 캡슐화를 깨트림. 부모 클래스의 변경에 따라 자식 클래스가 의도치 않게 동작할수도, 혹은 자식 클래스에서 부모 클래스의 메서드를 오버라이딩을 잘 못 해서 원치 않는 결과가 수행될 수 있다고 해.
[블로그 참고](https://happy-playboy.tistory.com/entry/Item-18-%EC%83%81%EC%86%8D%EB%B3%B4%EB%8B%A4%EB%8A%94-%EC%BB%B4%ED%8F%AC%EC%A7%80%EC%85%98%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC)

상속 - 높은 결합도
컴포지션 - 구성요소들의 결합으로 클래스를 구성해 상속에 비해 비교적 낮은 결합도

**Comment by DongjunLim** [comment]
정적 메서드를 통해 인스턴스의 통제가 가능해진다고 설명하며, 플라이웨이트 패턴에 대해 이야기한다. 플라이웨이트 패턴은 인스턴스가 없다면 새로 생성하고, 인스턴스가 있다면 해당 인스턴스를 참조하는 디자인 패턴을 말하는데, 하나의 인스턴스를 여러 객체가 참조한다는게 싱글톤 패턴과 비슷해보이는데 플라이웨이트 패턴은 싱글톤 패턴과는 어떻게 다른걸까?

**Comment by syunyun** [comment]
@DongjunLim 

# 싱글톤, 플라이웨이트

- 싱글톤 패턴은  Creational Pattern,  플라이웨이트 패턴은 Structural Pattern
- Creational Pattern은 인스턴스를 `만드는 절차`를 추상화 시킨 패턴
- Structural 패턴은 작은 클래스들의 상속과 합성을 이용해서 더 큰 클래스를 생성하는 방법을 제공하는 패턴
- 싱글톤은은 어떤 이유 때문에  인스턴스가 메모리에 딱 한번만 올라가야한다. (로깅,DB 커넥션풀...)

## 싱글톤 구현

싱글톤을 구현하는 방식은 여러가지가 있다. 하지만, 쓰레드세이프 Synchronized로 인한 성능저하등의 이유로 일반적으로 `Bill Pugh Singleton Implementaion` 방식을 이용해서 구현한다.  private 생성자를 통해서 new 키워드로 인스턴스 생성하는것을 막고 있다. 또한 Inner 클래스를 통해서 생성하려는 인스턴스를 지연로딩 시켜서  `getInstance()` 하기전에는 인스턴스가 생성되지 않는다. 마지막으로 SingletonHelper내부 클래스가 로드될때 인스턴스가 로드되므로 멀티스레드환경에서 스레드세이프를 보장한다.

```java


public class Singleton {

  
   private Singleton(){}
    
   private static class SingletonHelper{
     private static final Singleton INSTANCE = new Singleton();
   }
    
   public static Singleton getInstance(){
     return SingletonHelper.INSTANCE;
   }
   }



```

## 플라이웨이트 구현

똑같은 인스턴스는 생기지 않지만 결국 내부 값은 다른 인스턴스가 여러개 생성된다. 다시한번 강조하지만 싱글톤은 애플리케이션 전역에서 단 한개의 인스턴스만 가져야한다.

```java
public class Flywight{
   private String data;
   public Flyweight(String data){
          this.data = data;
    }
    public String getData(){
         return data;
    }
}

public class FlyweightFactory{
    Map pool;
  
    public FlyweightFactory(){
        pool = new TreeMap();
    }
    public Flyweight getFlyweight(String key){
       Flyweight flyweight = pool.get(key);
       if(flyweight == null){
             flyweight = new Flyweight(key);
             pool.put(key, flyweight);
             System.out.println("NEW : "+ key);
       else{
             System.out.prinlln("REUSE : "+key);
        }
       return flyweight;
   }
}

public class Main{
    public static void main(String[] args){
      FlyweightFactory factory = new FlyweightFactory();
      
      Flyweight flyweight = factory.getFlyweight("A");
      System.out.prinln(flyweight);
      Flyweight flyweight = factory.getFlyweight("B");
      System.out.prinln(flyweight);
      Flyweight flyweight = factory.getFlyweight("C");
      System.out.prinln(flyweight);
      Flyweight flyweight = factory.getFlyweight("B");
      System.out.prinln(flyweight);
      Flyweight flyweight = factory.getFlyweight("A");
      System.out.prinln(flyweight);
      Flyweight flyweight = factory.getFlyweight("A");
      System.out.prinln(flyweight);
    }
}

```

**Comment by DongjunLim** [comment]
@syunyun 
눈높이 설명 👍👍
