### ISSUE TITLE
[아이템 2] 생성자에 매개변수가 많다면 빌더를 고려하라

### ISSUE THREAD

**Issue by syunyun** [org-study-java/effective-java#2]

**Comment by DongjunLim** [comment]
Lombok의 빌더 애노테이션을 통해 예제코드(2-4, 2-5, 2-6)와 같은 상속관계의 클래스도 빌더생성이 가능한가?????

**Comment by syunyun** [comment]
@DongjunLim 

@Builder 애노테이션을 자식클래스에 태깅시키면 컴파일 과정에서 에러가 발생한다.
자식 클래스의 생성자에 @Builder 애노테이션을 태깅하는 방법이 있다.

https://www.baeldung.com/lombok-builder-inheritance
https://tomining.tistory.com/182


Lombok 1.18.2 부터 실험기능으로 @SuperBuilder 애노테이션을 이용하면 상속관계의 객체를 빌더패턴으로 생성할 수 있다.

https://projectlombok.org/features/experimental/SuperBuilder

**Comment by syunyun** [comment]
@syunyun 

롬복은 어떻게 코드를 생성해줄까? 
어노테이션의 동작원리에 대해서 조사해보기

**Comment by DongjunLim** [comment]
@syunyun 

javac가 컴파일할때 AbstractSystexTree(AST)를 파싱하고,
javac가 롬복 패키지에 있는 javax.annotation.processing.Processor 파일을 읽고,
롬복을 annotation processor에 등록함.
그리고나서 aanotation processor가 AST를 동적으로 수정(코드 추가)함.

https://medium.com/@jason_kim/annotation-processing-101-%EB%B2%88%EC%97%AD-be333c7b913
https://free-strings.blogspot.com/2015/12/lombok.html
https://programmer.help/blogs/ten-minutes-to-understand-the-use-and-principle-of-lombok.html
