### ISSUE TITLE
[아이템 5] 자원을 직접 명시하지 말고 의존 객체 주입을 사용하라

### ISSUE THREAD

**Issue by DongjunLim** [org-study-java/effective-java#9]

**Comment by DongjunLim** [comment]
의존성 주입을 할 때 쓰는 Autowired 애노테이션을 
매개변수에 직접 붙이는 것과 생성자에 붙이는 것은 어떤 차이가 있는가??

**Comment by syunyun** [comment]
@DongjunLim 

스프링에서 기본적으로 필드익젝션을 비추하고 생성자 주입을 권고함 @Autowired를 생성자에 태깅시키는 방법은 생성자 주입방법인데 Spring 4.3부터는 생성자에 주입하려는 대상을 명시만해도 자동으로 @Autowired가 태깅되기 때문에 붙여주지 않아도 상관없음 

생성자 주입을 권고하는 이유?

> 순환참조를 잡아낼수있고 final 키워드를 통해서 주입시킨 객체를 변경시킬 수 없도록 한다.

필드인젝션 : final사용 불가능, 순환참조 문제 발생
생성자주입 : final사용 가능, 순환참조 컴파일 타임에서 체크가능

필드인잭션은 빈을 생성한 후 @Autowired가 태깅된 빈을 찾아서 주입하는 방식이다. 빈을 먼저 생성시키고나서 의존객체를 주입받는다.
생성자주입은 빈이 생성되는 시점에 생성자의 인자로 사용되는 의존객체(빈)을 찾거나 빈팩토리를 이용해서 생성시키고 해당 의존객체(빈)들을 빈에 주입시키면서 생성된다.
